apiVersion: batch/v1
kind: Job
metadata: 
  name: timedelay-job
  labels:
    env: "test"
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      name: test-delay-job-pod
      labels:
        env: "test"
    spec:
      restartPolicy: OnFailure
      containers:
        - image:  luksa/batch-job
          name:  my-name
      