apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: test-cronjob-1
spec:
  schedule: "38 2 * * *"
  startingDeadlineSeconds: 15
  jobTemplate:
    spec:
      template:
        metadata:
          name: test-cronjob-timedelay
        spec:
          restartPolicy: OnFailure
          containers:
            - image:  luksa/batch-job
              name:  my-name
            