
apiVersion: v1
kind: ReplicationController
metadata:
        name: aviva-test-myapp-rc
        generateName: aviva-test
        labels:
                client: "Aviva"
                owner: "BDS"
spec:
        replicas: 3
        selector:
                appName: "Proflow"
        template:
                metadata:
                        name: "Proflow"
                        labels:
                                env: "Test"
                                appName: "Proflow"
                                client: "Aviva"
                                owner: "BDS"
                spec:
                        containers:
                                -  name: proflow-web
                                   image: nginx:latest
                                   ports:
                                           -  containerPort: 80
                                              protocol: TCP
                                
